# For details see:
# - https://golangci-lint.run/usage/configuration/
# - https://golangci-lint.run/usage/linters/

run:
  issues-exit-code: 2
  modules-download-mode: readonly

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
