name: Docker build and push

on: push

jobs:
  build:
    name: Build and push docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install -y make

    - name: Build docker container
      run: make image

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: evelinfong1/daytona
        tag_with_ref: true
        dockerfile: ./Dockerfile
